#!/bin/bash


MSHELL_TYPE=mysql
#MSHELL_USER=
#MSHELL_HOST=

MSHELL_WORKING=./

MSHELL_DBNAME=log
MSHELL_DBPWD=secret
MSHELL_DBUID=hc_log
MSHELL_DBHOST=192.168.119.162

MSHELL_COMMAND=""

source ${MSHELL_WORKING}/.config/proxy.sh
source ${MSHELL_WORKING}/.config/shell.sh
